---
name: "Bug"
description: Bug
title: "A Bug issue"
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes: 
      value: "## BUG!"
  - type: textarea
    attributes:
      label: "What's wrong?"
