name: Handle Non-labeled Issues
on:
  issues:
    types: [opened]
permissions:
  issues: write

jobs:
  handle_non_labeled_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/handle-non-labeled-issues
        with:
          labels: |
            needs-triage
          message: >
            Hi! This issue was created via the API, so it didn't have a label
            and may be missing some information. Please use the issue template
            through the GitHub web interface next time to ensure that we have
            all the information we need to help you.
